const path = require('path');

const defaultMes = `This file is auto generated by gen-dir`;

const dirPath = (...rest) => path.resolve(...rest);

const cppDefault = (name = 'TASK', options = { type: 'basic' }) => {
	const code = {
		basic: `#include <bits/stdc++.h>
using namespace std;

int main() {
	// freopen("./in/${name}.INP", "r", stdin);
	// freopen("./out/${name}.OUT", "w", stdout);
	cout << "${defaultMes}";
	return 0;
}`,
		brute: `#include <bits/stdc++.h>
using namespace std;

int main() {
	// freopen("./in/${name}.INP", "r", stdin);
	// freopen("./out/${name}.OUT", "w", stdout);
	cout << "${defaultMes}";
	return 0;
}`,
		gene: `#include <bits/stdc++.h>
using namespace std;

int main() {
	// freopen("../in/${name}.INP", "r", stdin);
	// freopen("../out/${name}.OUT", "w", stdout);
	cout << "${defaultMes}";
	return 0;
}`,
		fc: `#include <bits/stdc++.h>
using namespace std;

int main() {
	// freopen("../in/${name}.INP", "w", stdout);
	cout << "${defaultMes}";
	return 0;
}`,
	};

	if (!(options.type in code)) options.type = 'basic';
	return code[options.type];
};

module.exports = { defaultMes, dirPath, cppDefault };
